" This vimscript should be sourced under REPO_ROOT/test.
set nocompatible
if exists("$VIM_BUNDLE_PATH")
    " For Github workflows.
    let &rtp .= "," . expand("$VIM_BUNDLE_PATH") . "/vader.vim"
    let &rtp .= "," . expand("$VIM_BUNDLE_PATH") . "/vim-repeat"
else
    set rtp+=~/.vim/bundle/vader.vim
    set rtp+=~/.vim/bundle/vim-repeat
endif
set rtp+=..
filetype plugin indent on
if has("nvim")
    if isdirectory("venv")
        let g:python3_host_prog = "venv/bin/python3"
    elseif isdirectory(".venv")
        let g:python3_host_prog = ".venv/bin/python3"
    else
        " For Github workflows.
        let g:python3_host_prog = trim(system("which python3"))
    endif
endif
