" This vimscript should be sourced under REPO_ROOT/test.
set nocompatible
set rtp+=~/.vim/bundle/vader.vim
set rtp+=..
filetype plugin indent on
if has("nvim")
    let g:python3_host_prog = "venv/bin/python3"
endif
