version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust_backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust_backend/jieba_vim_rs_core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust_backend/jieba_vim_rs_test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/rust_backend/jieba_vim_rs_test_macro"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    # pyproject.toml is supported for pip since dependabot v2
