version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust_backend"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns:
          - '*'
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    groups:
      integration-test-deps:
        patterns:
          - '*'
    # pyproject.toml is supported for pip since dependabot v2
