version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust_backend"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 15
      semver-major-days: 30
      semver-minor-days: 15
      semver-patch-days: 7
    groups:
      rust-deps:
        patterns:
          - '*'
  - package-ecosystem: "pip"
    directory: "/dev_scripts"
    schedule:
      interval: "monthly"
    groups:
      dev-scripts-deps:
        patterns:
          - '*'
