repos:
  - repo: https://github.com/google/vimdoc
    rev: v0.7.1
    hooks:
    - id: vimdoc
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo clippy check (rust_backend)
        entry: cargo clippy --all-targets --workspace --manifest-path rust_backend/Cargo.toml
        language: system
        always_run: true
        pass_filenames: false
      - id: cargo-fmt-check
        name: cargo format check (rust_backend)
        entry: cargo fmt --all --check --manifest-path rust_backend/Cargo.toml
        language: system
        types: [rust]
        pass_filenames: false
      - id: outdated-copyright-check
        name: outdated copyright notice check
        entry: uv run --locked --project dev_scripts dev_scripts/check_copyright.py
        language: system
        always_run: true
        pass_filenames: true
      - id: dbg-check
        name: dbg macro check
        entry: uv run --locked --project dev_scripts dev_scripts/check_dbg.py
        language: system
        types: [rust]
        pass_filenames: true
