name: CD

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  check-for-release:
    name: Check for release
    runs-on: ubuntu-latest
    outputs:
      release-tag-name: ${{ steps.is-release.outputs.RELEASE_TAG_NAME }}
    steps:
      - name: Check for release info in PR title
        id: is-release
        shell: bash
        run: |
          unset TAG_NAME
          cat <<'EOF' > PR_TITLE
          ${{ github.event.pull_request.title }}
          EOF
          cat PR_TITLE
          TAG_NAME=
          if grep -q '^Release: v' PR_TITLE; then
            TAG_NAME="$(cat PR_TITLE | cut -c10-)"
          fi
          echo "RELEASE_TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

  ensure-release:
    name: Ensure current pull request is a release
    runs-on: ubuntu-latest
    needs:
      - check-for-release
    if: needs.check-for-release.outputs.release-tag-name != ''
    steps:
      - name: Pass through
        shell: bash
        run: exit 0

  check-source-branch:
    name: Check pull request source branch
    runs-on: ubuntu-latest
    needs:
      - check-for-release
      - ensure-release
    if: github.base_ref == 'release'
    steps:
      - name: Verify that the PR source branch is main
        if: github.head_ref != 'main'
        shell: bash
        run: |
          echo "E: Pull requests targeting 'release' branch must originate from 'main'." >&2
          echo "E: Current source branch: ${{ github.head_ref }}" >&2
          exit 1

  # Reference: https://github.com/sharkdp/fd/blob/master/.github/workflows/CICD.yml
  # Reference: https://github.com/mlua-rs/mlua/blob/main/.github/workflows/main.yml
  build:
    name: Build binding ${{ matrix.binding }} for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: true
      matrix:
        binding:
          - py3
          - lua51
        job:
          # This is enabled because wall time check in unit tests has been
          # removed. But the issue might not be resolved yet. See more at
          # https://github.com/kkew3/jieba.vim/issues/8.
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-14
          # macos-15-intel runner is only valid until August 2027. We will need
          # to revert this change after that.
          - target: x86_64-apple-darwin
            os: macos-15-intel
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
      - uses: actions/checkout@v6

      - name: Install ARM compiler toolchain
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            aarch64-unknown-linux-gnu)
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
              ;;
          esac

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}
          toolchain: stable

      - name: Show version information (Rust, cargo, gcc)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          rustup target list | grep installed
          cargo -V
          rustc -V

      - name: Build
        shell: bash
        run: |
          cargo build --locked --release --target=${{ matrix.job.target }} \
            --manifest-path rust_backend/Cargo.toml \
            --package jieba_vim_rs_binding_${{ matrix.binding }}

      - name: Set cdylib name and path
        id: cdylib
        shell: bash
        run: |
          case ${{ matrix.binding }} in
            py3)            LIB_NAME=jieba_vim_rs;                       ;;
            lua51)          LIB_NAME=jieba_vim_jieba_vim_rs;             ;;
          esac
          case ${{ matrix.job.target }} in
            *-linux-*)      CDYLIB_SUFFIX=".so";    CDYLIB_PREFIX="lib"; ;;
            *-apple-darwin) CDYLIB_SUFFIX=".dylib"; CDYLIB_PREFIX="lib"; ;;
            *-pc-windows-*) CDYLIB_SUFFIX=".dll";   CDYLIB_PREFIX="";    ;;
          esac

          CDYLIB_NAME=${CDYLIB_PREFIX}${LIB_NAME}${CDYLIB_SUFFIX}
          LIB_PATH="$GITHUB_WORKSPACE/rust_backend/target/${{ matrix.job.target }}/release/${CDYLIB_NAME}"
          test -f "$LIB_PATH"

          echo "CDYLIB_SUFFIX=$CDYLIB_SUFFIX" >> $GITHUB_OUTPUT
          echo "LIB_PATH=$LIB_PATH" >> $GITHUB_OUTPUT

      - name: Rename dylib
        id: package
        shell: bash
        run: |
          LIB_NAME=jieba_vim_rs
          PKG_BASEDIR="$GITHUB_WORKSPACE/packages"
          mkdir -p "$PKG_BASEDIR" && cd "$PKG_BASEDIR"
          TO_NAME="${LIB_NAME}-${{ matrix.job.target }}-${{ matrix.binding }}${{ steps.cdylib.outputs.CDYLIB_SUFFIX }}"
          cp "${{ steps.cdylib.outputs.LIB_PATH }}" "$TO_NAME"
          test -f "${PKG_BASEDIR}/${TO_NAME}"
          echo "PKG_PATH=${PKG_BASEDIR}/${TO_NAME}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v6
        with:
          name: cdylib-pkg-${{ matrix.job.target }}-${{ matrix.binding }}
          path: ${{ steps.package.outputs.PKG_PATH }}
          if-no-files-found: error
          retention-days: 5
          compression-level: 0

  test-install:
    name: >
      Test install
      ${{ matrix.install-mode }}
      on ${{ matrix.vim.os }}
      with ${{ matrix.vim.distr }}
    runs-on: ${{ matrix.vim.os }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        install-mode:
          - download
          - source
        vim:
          - distr: vim
            version: v9.1.0000
            glue-lang: py311
            os: ubuntu-24.04
          - distr: nvim
            version: v0.11.5
            glue-lang: lua51
            os: ubuntu-24.04
          - distr: nvim
            version: v0.11.5
            glue-lang: lua51
            os: windows-latest
          - distr: nvim
            version: v0.11.5
            glue-lang: lua51
            os: macos-14
    env:
      # build variables
      JIEBA_VIM_BUILD_FROM_SOURCE: ${{ matrix.install-mode == 'source' && '1' || '' }}
      JIEBA_VIM_DOWNLOAD_BASE_URL: ${{ matrix.install-mode == 'download' && 'http://127.0.0.1:8000' || '' }}
      # uv variables
      UV_PROJECT: ${{ github.workspace }}/test/jieba_test_metatest
      UV_PYTHON_DOWNLOADS: automatic
      UV_MANAGED_PYTHON: '1'
      # sanity check vimrc variables
      GLUE_LANG: ${{ matrix.vim.glue-lang }}
      JIEBA_VIM_DIR: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-vim
        with:
          vim-distr: ${{ matrix.vim.distr }}
          vim-version: ${{ matrix.vim.version }}
          glue-lang: ${{ matrix.vim.glue-lang }}
      - uses: dtolnay/rust-toolchain@stable
        if: matrix.install-mode == 'source'
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: '0.11.16'
          enable-cache: true
      - name: Collect released artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: cdylib-pkg-*
          path: ~/dist
          merge-multiple: true
      - name: Serve local release page
        shell: bash
        run: |
          uv python install 3.11
          uv run --no-sync -p 3.11 -m http.server -b 127.0.0.1 -d ~/dist 8000 &
          sleep 10
          if [ -n "$JIEBA_VIM_DOWNLOAD_BASE_URL" ]; then
            curl -I "$JIEBA_VIM_DOWNLOAD_BASE_URL"
          fi
      - name: Run Vim install script
        shell: bash
        run: |
          case ${{ matrix.vim.distr }} in
            vim)
              vim -Nu NONE -n -Es \
                +"set rtp^=." \
                +"runtime plugin/jieba_vim.vim" \
                +"call jieba_vim#install()" \
                +"qa"
              ;;
            nvim)
              nvim --headless -u NONE --clean \
                +"set rtp^=." \
                +"runtime plugin/jieba_vim.vim" \
                +"call jieba_vim#install()" \
                +"qa"
              ;;
          esac
      - shell: bash
        run: uv sync
      - name: Post-install sanity check
        shell: bash
        run: |
          case ${{ matrix.vim.distr }} in
            vim)
              uv run jieba-metatest-i-test \
                --rc test/cases/vimrc \
                -v vim \
                -d i_test \
                test/cases/hanzi_sanity.jieba_test_case
              ;;
            nvim)
              uv run jieba-metatest-i-test \
                --rc test/cases/vimrc \
                -v nvim --neovim \
                -d i_test \
                test/cases/hanzi_sanity.jieba_test_case
              ;;
          esac

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check-for-release
      - check-source-branch
      - build
      - test-install
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: cdylib-pkg-*
          merge-multiple: true
      - name: Publish cdylib
        uses: softprops/action-gh-release@v3
        with:
          files: |
            jieba_vim_rs-*
          tag_name: ${{ needs.check-for-release.outputs.release-tag-name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
