name: CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      release
    types:
      - opened
      - synchronize
      - closed

jobs:
  check-for-release:
    name: Check for release
    runs-on: ubuntu-latest
    outputs:
      release-tag-name: ${{ steps.is-release.outputs.RELEASE_TAG_NAME }}
    steps:
      - name: Check for release info in PR title
        id: is-release
        shell: bash
        run: |
          unset TAG_NAME
          cat <<EOF > PR_TITLE
          ${{ github.event.pull_request.title }}
          EOF
          cat PR_TITLE
          if ! grep -q '^Release: v' PR_TITLE; then
            echo "PR title must start with 'Release: v' followed by SemVer number" >&2
            exit 1
          fi
          TAG_NAME="$(cat PR_TITLE | cut -c10-)"
          echo "RELEASE_TAG_NAME=${TAG_NAME}" >> $GITHUB_OUTPUT

  # Reference: https://github.com/sharkdp/fd/blob/master/.github/workflows/CICD.yml
  # Reference: https://github.com/mlua-rs/mlua/blob/main/.github/workflows/main.yml
  build:
    name: Build binding ${{ matrix.binding }} for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: true
      matrix:
        binding:
          - py3
          - lua51
        job:
          # This is enabled because wall time check in unit tests has been
          # removed. But the issue might not be resolved yet. See more at
          # https://github.com/kkew3/jieba.vim/issues/8.
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-14
          # macos-15-intel runner is only valid until August 2027. We will need
          # to revert this change after that.
          - target: x86_64-apple-darwin
            os: macos-15-intel
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
      - uses: actions/checkout@v6

      - name: Install ARM compiler toolchain
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            aarch64-unknown-linux-gnu)
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
              ;;
          esac

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}
          toolchain: stable

      - name: Show version information (Rust, cargo, gcc)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          rustup target list | grep installed
          cargo -V
          rustc -V

      - name: Build
        shell: bash
        run: |
          cargo build --locked --release --target=${{ matrix.job.target }} \
            --manifest-path rust_backend/Cargo.toml \
            --package jieba_vim_rs_binding_${{ matrix.binding }}

      - name: Set cdylib name and path
        id: cdylib
        shell: bash
        run: |
          case ${{ matrix.binding }} in
            py3)            LIB_NAME=jieba_vim_rs;                       ;;
            lua51)          LIB_NAME=jieba_vim_jieba_vim_rs;             ;;
          esac
          case ${{ matrix.job.target }} in
            *-linux-*)      CDYLIB_SUFFIX=".so";    CDYLIB_PREFIX="lib"; ;;
            *-apple-darwin) CDYLIB_SUFFIX=".dylib"; CDYLIB_PREFIX="lib"; ;;
            *-pc-windows-*) CDYLIB_SUFFIX=".dll";   CDYLIB_PREFIX="";    ;;
          esac

          CDYLIB_NAME=${CDYLIB_PREFIX}${LIB_NAME}${CDYLIB_SUFFIX}
          LIB_PATH="$GITHUB_WORKSPACE/rust_backend/target/${{ matrix.job.target }}/release/${CDYLIB_NAME}"
          test -f "$LIB_PATH"

          echo "CDYLIB_SUFFIX=$CDYLIB_SUFFIX" >> $GITHUB_OUTPUT
          echo "LIB_PATH=$LIB_PATH" >> $GITHUB_OUTPUT

      - name: Rename dylib
        id: package
        shell: bash
        run: |
          LIB_NAME=jieba_vim_rs
          PKG_BASEDIR="$GITHUB_WORKSPACE/packages"
          mkdir -p "$PKG_BASEDIR" && cd "$PKG_BASEDIR"
          TO_NAME="${LIB_NAME}-${{ matrix.job.target }}-${{ matrix.binding }}${{ steps.cdylib.outputs.CDYLIB_SUFFIX }}"
          cp "${{ steps.cdylib.outputs.LIB_PATH }}" "$TO_NAME"
          test -f "${PKG_BASEDIR}/${TO_NAME}"
          echo "PKG_PATH=${PKG_BASEDIR}/${TO_NAME}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v6
        with:
          name: cdylib-pkg-${{ matrix.job.target }}-${{ matrix.binding }}
          path: ${{ steps.package.outputs.PKG_PATH }}
          if-no-files-found: error
          retention-days: 5
          compression-level: 0

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - check-for-release
      - build
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: cdylib-pkg-*
          merge-multiple: true
      - name: Publish cdylib
        uses: softprops/action-gh-release@v2
        with:
          files: |
            jieba_vim_rs-*
          tag_name: ${{ needs.check-for-release.outputs.release-tag-name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
