name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - rust
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - rust

jobs:
  unit_test_integration_test:
    name: "Unit test and integration test for ${{ matrix.vim.dist }} @ ${{ matrix.vim.version }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        vim:
          - dist: vim
            version: v8.2.0
          - dist: vim
            version: v9.1.0
          - dist: nvim
            version: v0.10.2
    steps:
      - uses: actions/checkout@v5
        with:
          path: jieba_vim
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Cache vim/nvim and vader.vim
        id: cache-vim
        uses: actions/cache@v4
        with:
          path: |
            vim
            vim_bundle
          key: vim-distro-${{ matrix.vim.dist }}-${{ matrix.vim.version }}

      - name: Install vim/nvim
        if: steps.cache-vim.outputs.cache-hit != 'true'
        run: |
          case ${{ matrix.vim.dist }} in
            vim)
              sudo apt-get update
              sudo apt-get install -y git make clang libtool-bin
              git clone https://github.com/vim/vim.git && cd vim
              git checkout ${{ matrix.vim.version }}
              # References:
              # - https://allanchain.github.io/blog/post/compile-vim-python3/
              case ${{ matrix.vim.version }} in
                v9.1.0)
                  LDFLAGS=-rdynamic ./configure \
                      --with-features=huge \
                      --enable-fail-if-missing \
                      --enable-largefile \
                      --enable-multibyte \
                      --enable-python3interp \
                      --with-python3-command=python3.11 \
                      --with-python3-stable-abi=3.11 \
                      --enable-gui=no \
                      --prefix="$GITHUB_WORKSPACE/vim/prefix"
                  ;;
                v8.2.0)
                  env \
                      vi_cv_path_python3_plibs="-L$(python3.11-config --configdir) -lpython3.11 -ldl -lm" \
                      vi_cv_var_python3_version=3.11 \
                      LDFLAGS=-rdynamic \
                      ./configure \
                      --with-features=huge \
                      --enable-fail-if-missing \
                      --enable-largefile \
                      --enable-multibyte \
                      --enable-python3interp \
                      --with-python3-command=python3.11 \
                      --with-python3-config-dir="$(python3.11-config --configdir)" \
                      --prefix="$GITHUB_WORKSPACE/vim/prefix"
                  ;;
              esac
              make -j4 && make install
              echo "$GITHUB_WORKSPACE/vim/prefix/bin" >> $GITHUB_PATH
              ;;
            nvim)
              sudo apt-get update
              sudo apt-get install -y curl tar
              cd "$GITHUB_WORKSPACE"
              mkdir vim
              # Extract nvim to "vim", so that it's easier to cache the result.
              curl -fsSL https://github.com/neovim/neovim/releases/download/${{ matrix.vim.version }}/nvim-linux64.tar.gz | tar xzf - --strip-components=1 -C vim
              echo "$GITHUB_WORKSPACE/vim/bin" >> $GITHUB_PATH
              ;;
          esac

      - name: Add vim/nvim to PATH
        if: steps.cache-vim.outputs.cache-hit == 'true'
        run: |
          case ${{ matrix.vim.dist }} in
            vim)
              echo "$GITHUB_WORKSPACE/vim/prefix/bin" >> $GITHUB_PATH
              ;;
            nvim)
              echo "$GITHUB_WORKSPACE/vim/bin" >> $GITHUB_PATH
              ;;
          esac

      - name: Ensure vim/nvim version
        run: |
          ${{ matrix.vim.dist }} --version

      - name: Install vader.vim and vim-repeat
        if: steps.cache-vim.outputs.cache-hit != 'true'
        run: |
          mkdir "$GITHUB_WORKSPACE/vim_bundle"
          git clone https://github.com/junegunn/vader.vim.git "$GITHUB_WORKSPACE/vim_bundle/vader.vim"
          git clone https://github.com/tpope/vim-repeat.git "$GITHUB_WORKSPACE/vim_bundle/vim-repeat"

      - name: Verify and run unit tests
        run: |
          export VIM_BUNDLE_PATH="$GITHUB_WORKSPACE/vim_bundle"
          export VIM_BIN_NAME=${{ matrix.vim.dist }}
          cd "$GITHUB_WORKSPACE/jieba_vim/rust_backend/jieba_vim_rs_core"
          cargo test -F verifiable_case --release

      - name: Build
        run: |
          cd "$GITHUB_WORKSPACE/jieba_vim/rust_backend"
          cargo build --locked --release --features=expose-shared-library

      - name: Install integration test dependencies
        run: |
          cd "$GITHUB_WORKSPACE/jieba_vim/test"
          pip install .

      - name: Run integration tests
        run: |
          cd "$GITHUB_WORKSPACE/jieba_vim/test"
          export VIM_BUNDLE_PATH="$GITHUB_WORKSPACE/vim_bundle"
          export VIM_BIN_NAME=${{ matrix.vim.dist }}
          pytest

  coverage:
    name: Test coverage
    runs-on: ubuntu-22.04
    needs: unit_test_integration_test
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-tarpaulin
        shell: bash
        run: cargo install cargo-tarpaulin
      - name: Show cargo-tarpaulin version
        shell: bash
        run: cargo tarpaulin --version
      - name: Run cargo-tarpaulin
        shell: bash
        run: |
          cargo tarpaulin --release --out Xml \
              --exclude-files 'jieba_vim_rs_test/*' \
              --exclude-files 'jieba_vim_rs_test_macro/*' \
              --exclude-files 'src/*' \
              --packages jieba_vim_rs_core \
              --manifest-path rust_backend/Cargo.toml
      - uses: codecov/codecov-action@v5
        with:
          files: rust_backend/cobertura.xml
          disable_search: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      

  # Reference: https://github.com/sharkdp/fd/blob/master/.github/workflows/CICD.yml
  # Reference: https://github.com/mlua-rs/mlua/blob/main/.github/workflows/main.yml
  build:
    name: Build for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    needs: unit_test_integration_test
    strategy:
      fail-fast: false
      matrix:
        job:
          # This is enabled because wall time check in unit tests has been
          # removed. But the issue might not be resolved yet. See more at
          # https://github.com/kkew3/jieba.vim/issues/8.
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-14
          # macos-15-intel runner is only valid until August 2027. We will need
          # to revert this change after that.
          - target: x86_64-apple-darwin
            os: macos-15-intel
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
      - uses: actions/checkout@v5
        with:
          path: jieba_vim

      - name: Install ARM compiler toolchain
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            aarch64-unknown-linux-gnu)
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross
              ;;
          esac

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}
          toolchain: stable

      - name: Show version information (Rust, cargo, gcc)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          rustup target list | grep installed
          cargo -V
          rustc -V

      - name: Build
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE/jieba_vim/rust_backend" && cargo build --locked --release --target=${{ matrix.job.target }}
