name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

jobs:
  build-jieba-vim-cdylib:
    name: Build jieba.vim cdylib required in verifications
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Build py3 binding
        shell: bash
        run: |
          rm -f jieba_vim_rs.so
          cargo clean \
            --manifest-path rust_backend/Cargo.toml
          cargo build --locked -r \
            --manifest-path rust_backend/Cargo.toml \
            --package jieba_vim_rs_binding_py3
          mv rust_backend/target/release/libjieba_vim_rs.so jieba_vim_rs.so
      - uses: actions/upload-artifact@v6
        with:
          name: jieba-vim-cdylib-python
          path: jieba_vim_rs.so
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - name: Build lua51 binding
        shell: bash
        run: |
          rm -f jieba_vim_rs.so
          cargo clean \
            --manifest-path rust_backend/Cargo.toml
          cargo build --locked -r \
            --manifest-path rust_backend/Cargo.toml \
            --package jieba_vim_rs_binding_lua51
          mv rust_backend/target/release/libjieba_vim_jieba_vim_rs.so jieba_vim_rs.so
      - uses: actions/upload-artifact@v6
        with:
          name: jieba-vim-cdylib-lua
          path: jieba_vim_rs.so
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  pytest-metatest:
    name: Pytest metatest
    runs-on: ubuntu-24.04
    env:
      # uv variables
      UV_PROJECT: ${{ github.workspace }}/test/jieba_test_metatest
      UV_PYTHON_DOWNLOADS: automatic
      UV_MANAGED_PYTHON: '1'
      # pytest variables
      CI: '1'
    steps:
      - uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: '0.11.16'
          enable-cache: true
      - name: Run uv-sync
        shell: bash
        run: uv sync --extra dev
      - name: Run test on metatest
        shell: bash
        run: uv run pytest $UV_PROJECT

  basic-integrated-verification:
    name: >
      Basic integrated case verification for
      ${{ matrix.vim.distr }}@${{ matrix.vim.version }}
      +${{ matrix.vim.glue-lang }}
    runs-on: ubuntu-24.04
    needs:
      - build-jieba-vim-cdylib
    strategy:
      fail-fast: false
      matrix:
        vim:
          - distr: vim
            version: v8.2.3455
            glue-lang: py39
          - distr: vim
            version: v9.1.0000
            glue-lang: py311
    env:
      # uv variables
      UV_PROJECT: ${{ github.workspace }}/test/jieba_test_metatest
      UV_PYTHON_DOWNLOADS: automatic
      UV_MANAGED_PYTHON: '1'
      # vimrc variables
      GLUE_LANG: ${{ matrix.vim.glue-lang }}
      JIEBA_VIM_DIR: ${{ github.workspace }}
    steps:
      # Prepare env.
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-vim
        with:
          vim-distr: ${{ matrix.vim.distr }}
          vim-version: ${{ matrix.vim.version }}
          glue-lang: ${{ matrix.vim.glue-lang }}
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: '0.11.16'
          enable-cache: true
      - name: Run uv-sync
        shell: bash
        run: uv sync
      - name: Expand basic integrated cases template
        shell: bash
        run: make -C test/cases/basic_integrated_verification clean all
      - name: Get jieba.vim cdylib for +python3
        if: matrix.vim.glue-lang == 'py311' || matrix.vim.glue-lang == 'py39'
        uses: actions/download-artifact@v7
        with:
          name: jieba-vim-cdylib-python
          path: pythonx/jieba_vim
      - name: Get jieba.vim cdylib for nvim/+lua
        if: matrix.vim.glue-lang == 'lua51'
        uses: actions/download-artifact@v7
        with:
          name: jieba-vim-cdylib-lua
          path: lua/jieba_vim
      - name: Vim sanity check
        shell: bash
        run: |
          cd test/cases/basic_integrated_verification
          case ${{ matrix.vim.distr }} in
            vim)
              vim -es -u vimrc -cq < /dev/null
              ;;
            nvim)
              nvim --headless -u vimrc -cq < /dev/null
              ;;
          esac
      - name: Get a filename-safe version of vim.version
        id: safe-version
        shell: bash
        run: |
          SAFE_VERSION="$(echo "${{ matrix.vim.version }}" | tr . _)"
          echo "safe_version=${SAFE_VERSION}" >> "$GITHUB_OUTPUT"
          echo "vim_dist_name=${{ matrix.vim.distr }}_${SAFE_VERSION}_${{ matrix.vim.glue-lang }}" >> "$GITHUB_OUTPUT"

      # Do the job.
      - name: Run basic integrated case verification
        id: run-bi-case-verification
        continue-on-error: true
        shell: bash
        run: |
          set +e
          case ${{ matrix.vim.distr }} in
            vim)
              uv run jieba-metatest-bi-verification \
                -j4 \
                --rc test/cases/basic_integrated_verification/vimrc \
                -v vim \
                -d bi_verification \
                -n ${{ steps.safe-version.outputs.vim_dist_name }} \
                -w bi_verification/warns_${{ steps.safe-version.outputs.vim_dist_name }} \
                -f bi_verification/errs_${{ steps.safe-version.outputs.vim_dist_name }} \
                test/cases/basic_integrated_verification/*.jieba_test_case
              ;;
            nvim)
              uv run jieba-metatest-bi-verification \
                -j4 \
                --rc test/cases/basic_integrated_verification/vimrc \
                -v nvim --neovim \
                -d bi_verification \
                -n ${{ steps.safe-version.outputs.vim_dist_name }} \
                -w bi_verification/warns_${{ steps.safe-version.outputs.vim_dist_name }} \
                -f bi_verification/errs_${{ steps.safe-version.outputs.vim_dist_name }} \
                test/cases/basic_integrated_verification/*.jieba_test_case
              ;;
          esac
          exit_code=$?
          set -e
          echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
          if [ $exit_code != 0 ]; then
            false
          fi
      - name: Check basic integrated case verification exit code
        shell: bash
        run: |
          code="${{ steps.run-bi-case-verification.outputs.exit_code }}"
          if [ "$code" != 0 ] && [ "$code" != 1 ] && [ "$code" != 125 ]; then
            echo "bi case verification may have panicked" >&2
            false
          fi
      - name: Indicate whether basic integrated case verification has failed
        id: indicate-state
        shell: bash
        run: |
          TOFILE=bi-success-${{ steps.safe-version.outputs.vim_dist_name }}.txt
          echo "tofile=$TOFILE" >> "$GITHUB_OUTPUT"
          cat <<'EOF' > "$TOFILE"
          ${{ steps.run-bi-case-verification.outputs.exit_code }} ${{ matrix.vim.distr }} @${{ matrix.vim.version }} +${{ matrix.vim.glue-lang }}
          EOF
      - uses: actions/upload-artifact@v6
        with:
          name: bi-success-${{ matrix.vim.distr }}-${{ matrix.vim.version }}-${{ matrix.vim.glue-lang }}
          path: ${{ steps.indicate-state.outputs.tofile }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - uses: actions/upload-artifact@v6
        with:
          name: bi-report-${{ matrix.vim.distr }}-${{ matrix.vim.version }}-${{ matrix.vim.glue-lang }}
          path: |
            bi_verification/warns_${{ steps.safe-version.outputs.vim_dist_name }}
            bi_verification/errs_${{ steps.safe-version.outputs.vim_dist_name }}
          retention-days: 5
      - name: Collect rust test info jsonl files
        uses: actions/upload-artifact@v6
        with:
          name: rust-core-test-info-${{ matrix.vim.distr }}-${{ matrix.vim.version }}-${{ matrix.vim.glue-lang }}
          path: bi_verification/unit-${{ steps.safe-version.outputs.vim_dist_name }}.jsonl
          if-no-files-found: error
          retention-days: 5

  report-basic-integrated-case-verification-errors:
    name: Report basic integrated case verification errors
    runs-on: ubuntu-24.04
    needs: basic-integrated-verification
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: bi-success-*
          merge-multiple: true
      - uses: actions/download-artifact@v7
        with:
          pattern: bi-report-*
          merge-multiple: true
      - name: Report errors
        shell: bash
        run: |
          for file in $(find . -type f -name 'errs_*'); do
            echo "$file -->"
            cat "$file"
          done
          echo "==="
          ! cat bi-success-*.txt | grep '^1 '

  report-basic-integrated-case-verification-warnings:
    name: Report basic integrated case verification warnings
    runs-on: ubuntu-24.04
    needs: basic-integrated-verification
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: bi-success-*
          merge-multiple: true
      - uses: actions/download-artifact@v7
        with:
          pattern: bi-report-*
          merge-multiple: true
      - name: Report warnings
        shell: bash
        run: |
          for file in $(find . -type f -name 'warns_*'); do
            echo "$file -->"
            cat "$file"
          done
          echo "==="
          ! cat bi-success-*.txt | grep '^125 '

  integrated-test:
    name: >
      Integrated test for
      ${{ matrix.vim.distr }}@${{ matrix.vim.version }}
      +${{ matrix.vim.glue-lang }}
    runs-on: ubuntu-24.04
    needs:
      - build-jieba-vim-cdylib
    strategy:
      fail-fast: false
      matrix:
        vim:
          - distr: vim
            version: v8.2.3455
            glue-lang: py39
          - distr: vim
            version: v9.1.0000
            glue-lang: py311
          - distr: nvim
            version: v0.10.2
            glue-lang: lua51
          - distr: nvim
            version: v0.11.5
            glue-lang: lua51
    env:
      # uv variables
      UV_PROJECT: ${{ github.workspace }}/test/jieba_test_metatest
      UV_PYTHON_DOWNLOADS: automatic
      UV_MANAGED_PYTHON: '1'
      # vimrc variables
      GLUE_LANG: ${{ matrix.vim.glue-lang }}
      JIEBA_VIM_DIR: ${{ github.workspace }}
      VIM_REPEAT_DIR: ${{ github.workspace }}/.vim_bundle/vim-repeat
    steps:
      # Prepare env.
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-vim
        with:
          vim-distr: ${{ matrix.vim.distr }}
          vim-version: ${{ matrix.vim.version }}
          glue-lang: ${{ matrix.vim.glue-lang }}
      - name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: '0.11.16'
          enable-cache: true
      - name: Run uv-sync
        shell: bash
        run: uv sync
      - name: Get jieba.vim cdylib for +python3
        if: matrix.vim.glue-lang == 'py311' || matrix.vim.glue-lang == 'py39'
        uses: actions/download-artifact@v7
        with:
          name: jieba-vim-cdylib-python
          path: pythonx/jieba_vim
      - name: Get jieba.vim cdylib for nvim/+lua
        if: matrix.vim.glue-lang == 'lua51'
        uses: actions/download-artifact@v7
        with:
          name: jieba-vim-cdylib-lua
          path: lua/jieba_vim
      - name: Get a filename-safe version of vim.version
        id: safe-version
        shell: bash
        run: |
          SAFE_VERSION="$(echo "${{ matrix.vim.version }}" | tr . _)"
          echo "safe_version=${SAFE_VERSION}" >> "$GITHUB_OUTPUT"
          echo "vim_dist_name=${{ matrix.vim.distr }}_${SAFE_VERSION}_${{ matrix.vim.glue-lang }}" >> "$GITHUB_OUTPUT"
      - name: Expand templates
        shell: bash
        run: make -C test/cases clean all
      - name: Setup vim plugins
        shell: bash
        run: |
          mkdir -p .vim_bundle
          git clone https://github.com/tpope/vim-repeat.git .vim_bundle/vim-repeat

      # Do the job.
      - name: Run integrated test
        id: run-i-test
        continue-on-error: true
        shell: bash
        run: |
          cum_exit_code=
          for dir in $(find test/cases -maxdepth 1 -type d); do
            set +e
            case ${{ matrix.vim.distr }} in
              vim)
                uv run jieba-metatest-i-test \
                  --rc $dir/vimrc \
                  -v vim \
                  -d i_test \
                  -w i_test/warns_${{ steps.safe-version.outputs.vim_dist_name }} \
                  -f i_test/errs_${{ steps.safe-version.outputs.vim_dist_name }} \
                  $dir/*.jieba_test_case
                ;;
              nvim)
                uv run jieba-metatest-i-test \
                  --rc $dir/vimrc \
                  -v nvim --neovim \
                  -d i_test \
                  -w i_test/warns_${{ steps.safe-version.outputs.vim_dist_name }} \
                  -f i_test/errs_${{ steps.safe-version.outputs.vim_dist_name }} \
                  $dir/*.jieba_test_case
                ;;
            esac
            exit_code=$?
            set -e
            if [ $exit_code != 0 ] && [ $exit_code != 125 ]; then
              echo "exit_code=$exit_code" >> "$GITHUB_OUTPUT"
              false
            fi
            if [ -z "$cum_exit_code" ]; then
              cum_exit_code=$exit_code
            elif [ $exit_code = 125 ]; then
              cum_exit_code=125
            fi
          done
          echo "exit_code=$cum_exit_code" >> "$GITHUB_OUTPUT"
      - name: Check integrated test exit code
        shell: bash
        run: |
          code="${{ steps.run-i-test.outputs.exit_code }}"
          if [ "$code" != 0 ] && [ "$code" != 1 ] && [ "$code" != 125 ]; then
            echo "bi case verification may have panicked" >&2
            false
          fi
      - name: Indicate whether integrated test has failed
        id: indicate-state
        shell: bash
        run: |
          TOFILE=i-success-${{ steps.safe-version.outputs.vim_dist_name }}.txt
          echo "tofile=$TOFILE" >> "$GITHUB_OUTPUT"
          cat <<'EOF' > "$TOFILE"
          ${{ steps.run-i-test.outputs.exit_code }} ${{ matrix.vim.distr }} @${{ matrix.vim.version }} +${{ matrix.vim.glue-lang }}
          EOF
      - uses: actions/upload-artifact@v6
        with:
          name: i-success-${{ matrix.vim.distr }}-${{ matrix.vim.version }}-${{ matrix.vim.glue-lang }}
          path: ${{ steps.indicate-state.outputs.tofile }}
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
      - uses: actions/upload-artifact@v6
        with:
          name: i-report-${{ matrix.vim.distr }}-${{ matrix.vim.version }}-${{ matrix.vim.glue-lang }}
          path: |
            i_test/warns_${{ steps.safe-version.outputs.vim_dist_name }}
            i_test/errs_${{ steps.safe-version.outputs.vim_dist_name }}
          retention-days: 5

  report-integrated-test-errors:
    name: Report integrated test errors
    runs-on: ubuntu-24.04
    needs: integrated-test
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: i-success-*
          merge-multiple: true
      - uses: actions/download-artifact@v7
        with:
          pattern: i-report-*
          merge-multiple: true
      - name: Report errors
        shell: bash
        run: |
          for file in $(find . -type f -name 'errs_*'); do
            echo "$file -->"
            cat "$file"
          done
          echo "==="
          ! cat i-success-*.txt | grep '^1 '

  report-integrated-test-warnings:
    name: Report integrated test warnings
    runs-on: ubuntu-24.04
    needs: integrated-test
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: i-success-*
          merge-multiple: true
      - uses: actions/download-artifact@v7
        with:
          pattern: i-report-*
          merge-multiple: true
      - name: Report errors
        shell: bash
        run: |
          for file in $(find . -type f -name 'warns_*'); do
            echo "$file -->"
            cat "$file"
          done
          echo "==="
          ! cat i-success-*.txt | grep '^125 '

  rust-core-test:
    name: Run rust core tests
    runs-on: ubuntu-24.04
    needs: basic-integrated-verification
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Run unit tests of jieba_vim_rs_test
        shell: bash
        run: cargo test -r --manifest-path rust_backend/jieba_vim_rs_test/Cargo.toml
      - name: Run unit tests of jieba_vim_rs_core
        shell: bash
        run: cargo test -r --manifest-path rust_backend/jieba_vim_rs_core/Cargo.toml
      - uses: actions/download-artifact@v7
        with:
          path: rust_backend/jieba_vim_rs_core
          pattern: rust-core-test-info-*
          merge-multiple: true
      - name: Run Golden Master integration tests of jieba_vim_rs_core
        shell: bash
        run: |
          cd rust_backend/jieba_vim_rs_core
          cargo test -r --test golden_master -- unit-*.jsonl

  coverage:
    name: Test coverage
    runs-on: ubuntu-24.04
    needs: rust-core-test
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo-tarpaulin
        id: cache-cargo-tarpaulin
        uses: actions/cache@v5
        with:
          path: ~/.cargo/bin/cargo-tarpaulin
          key: cargo-tarpaulin
      - name: Install cargo-tarpaulin
        if: steps.cache-cargo-tarpaulin.outputs.cache-hit != 'true'
        shell: bash
        run: cargo install cargo-tarpaulin
      - name: Show cargo-tarpaulin version
        shell: bash
        run: cargo tarpaulin --version
      - uses: actions/download-artifact@v7
        with:
          path: rust_backend/jieba_vim_rs_core/golden_master_records
          pattern: rust-core-test-info-*
          merge-multiple: true
      - name: Run cargo-tarpaulin
        shell: bash
        run: |
          cd rust_backend
          # The working directory in the following command is:
          # rust_backend/jieba_vim_rs_core.
          GOLDEN_MASTER_DIR=golden_master_records \
            cargo tarpaulin --release --out Xml \
            --engine Llvm \
            --no-dead-code \
            --exclude-files 'jieba_vim_rs_test/*' \
            --exclude-files 'jieba_vim_rs_core/tests/*' \
            --exclude-files 'jieba_vim_rs_binding_lua51/*' \
            --exclude-files 'jieba_vim_rs_binding_py3/*' \
            --packages jieba_vim_rs_core
      - uses: codecov/codecov-action@v7
        with:
          files: rust_backend/cobertura.xml
          disable_search: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build for ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # This is enabled because wall time check in unit tests has been
          # removed. But the issue might not be resolved yet. See more at
          # https://github.com/kkew3/jieba.vim/issues/8.
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: aarch64-apple-darwin
            os: macos-14
          # macos-15-intel runner is only valid until August 2027. We will need
          # to revert this change after that.
          - target: x86_64-apple-darwin
            os: macos-15-intel
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    steps:
      - uses: actions/checkout@v6
      - name: Install ARM compiler toolchain
        if: matrix.job.target == 'aarch64-unknown-linux-gnu'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}
          toolchain: stable
      - name: Show version information (Rust, cargo, gcc)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          rustup target list | grep installed
          cargo -V
          rustc -V
      - name: Build
        shell: bash
        run: |
          cargo clean \
            --manifest-path rust_backend/Cargo.toml
          cargo build --locked -r \
            --target=${{ matrix.job.target }} \
            --package jieba_vim_rs_binding_lua51 \
            --manifest-path rust_backend/Cargo.toml
          cargo clean \
            --manifest-path rust_backend/Cargo.toml
          cargo build --locked -r \
            --target=${{ matrix.job.target }} \
            --package jieba_vim_rs_binding_py3 \
            --manifest-path rust_backend/Cargo.toml
