# Changes in lua/, pythonx/ and plugin/ directories invalidates all previous
# successful unit verifications in ci.yml. Hence, we need to delete those bad
# caches.
name: Remove outdated verification cache

on:
  # Ideally, this workflow should be run if and only if commits between last
  # pull request sync and current sync touches files under those directories.
  # But simply setting `pull_request.paths` to those directories will trigger
  # this workflow on *every* pull request sync. We may write a github script
  # that does the ideal check above (e.g. actions/github-script@v7). But for
  # now, we will be safe and let it run, saving the perfect automation to
  # future works.
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'lua/**'
      - 'pythonx/**'
      - 'plugin/**'
  push:
    branches:
      - rust
      - dev/rust
    paths:
      - 'lua/**'
      - 'pythonx/**'
      - 'plugin/**'

jobs:
  rm-outdated-unit-verfication-cache:
    name: Remove outdated unit verification cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Cleanup
        shell: bash
        run: |
          echo "Fetching list of outdated cache keys"
          gh cache list --key verified-unit- --limit 100

          echo "Deleting caches"
          set +e
          for key in $(gh cache list --key verified-unit- --limit 100 --json id --jq '.[].id'); do
            gh cache delete "$key"
          done
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
