name: Setup vim/nvim
description: Setup vim(+python3) / nvim
inputs:
  vim-distr:
    description: 'The vim/nvim distribution name (either "vim" or "nvim")'
    required: true
  vim-version:
    description: 'The vim/nvim version'
    required: true
  glue-lang:
    description: 'The glue language (either "py311", "py39" or "lua51")'
    required: true
runs:
  using: composite
  steps:
    - name: Check inputs to setup vim/nvim
      id: input-check
      shell: bash
      run: |
        case ${{ inputs.glue-lang }}-${{ inputs.vim-distr }}-${{ inputs.vim-version }} in
          py311-vim-v9.*)     ;;
          py39-vim-v9.*)      ;;
          py39-vim-v8.*)      ;;
          lua51-nvim-v*)      ;;
          *)
            echo unimplemented >&2
            exit 1
            ;;
        esac
        case ${{ inputs.glue-lang }} in
          py39)  echo "python_version=3.9" >> $GITHUB_OUTPUT;  ;;
          py311) echo "python_version=3.11" >> $GITHUB_OUTPUT; ;;
          *)     echo "python_version=" >> $GITHUB_OUTPUT;     ;;
        esac
    - name: Setup python ${{ steps.input-check.outputs.python_version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ steps.input-check.outputs.python_version }}
      if: ${{ steps.input-check.outputs.python_version != '' }}
    - name: Compile and install vim
      id: install-vim
      if: ${{ inputs.vim-distr == 'vim' }}
      uses: rhysd/action-setup-vim@v1.6.1
      with:
        version: ${{ inputs.vim-version }}
        configure-args: >
          --with-features=huge
          --enable-fail-if-missing
          --enable-largefile
          --enable-multibyte
          --enable-python3interp
          --with-python3-command=python${{ steps.input-check.outputs.python_version }}
          --with-python3-stable-abi=${{ steps.input-check.outputs.python_version }}
      env:
        LDFLAGS: '-rdynamic'
    - name: Download and install nvim
      id: install-nvim
      if: ${{ inputs.vim-distr == 'nvim' }}
      uses: rhysd/action-setup-vim@v1.6.1
      with:
        version: ${{ inputs.vim-version }}
        neovim: true
    - name: Add vim/nvim to PATH
      shell: bash
      run: |
        case ${{ inputs.vim-distr }} in
          vim)
            echo "$(dirname -- "${{ steps.install-vim.outputs.executable }}")" >> $GITHUB_PATH
            ;;
          nvim)
            echo "$(dirname -- "${{ steps.install-nvim.outputs.executable }}")" >> $GITHUB_PATH
            ;;
        esac
    - name: Print vim/nvim version
      shell: bash
      run: ${{ inputs.vim-distr }} --version
    - name: Vim +python3 sanity check
      if: ${{ inputs.vim-distr == 'vim' }}
      shell: bash
      run: vim -es -c'py3 pass' -cq
