name: Setup vim/nvim
description: Setup vim/nvim with +python3/+lua enabled
inputs:
  vim-distr:
    description: 'The vim/nvim distribution name (either "vim" or "nvim")'
    required: true
  vim-version:
    description: 'The vim/nvim version'
    required: true
  glue-lang:
    description: 'The glue language (either "py311", "py39" or "lua51")'
    required: true
runs:
  using: composite
  steps:
    - name: Check inputs to setup vim/nvim
      shell: bash
      run: |
        case ${{ inputs.glue-lang }}-${{ inputs.vim-distr }}-${{ inputs.vim-version }} in
          py311-vim-v9.*)     ;;
          py39-vim-v8.*)      ;;
          lua51-nvim-v0.10.2) ;;
          lua51-nvim-v0.11.5) ;;
          *)
            echo unimplemented >&2
            exit 1
            ;;
        esac
    - name: Setup python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
      if: ${{ inputs.glue-lang == 'py311' }}
    - name: Setup python 3.9
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
      if: ${{ inputs.glue-lang == 'py39' }}
    - name: Install pynvim
      shell: bash
      run: pip install pynvim
      if: ${{ inputs.glue-lang == 'py311' && inputs.vim-distr == 'nvim' }}
    - name: Cache vim/nvim directory
      id: cache-vim
      uses: actions/cache@v5
      with:
        key: ${{ inputs.vim-distr }}-${{ inputs.vim-version }}-${{ inputs.glue-lang }}
        path: ~/vim
    - name: Compile and install vim to PATH
      if: ${{ inputs.vim-distr == 'vim' && steps.cache-vim.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends git make clang libtool-bin
        git clone https://github.com/vim/vim.git ~/vim
        cd ~/vim && git checkout ${{ inputs.vim-version }}
        case "${{ inputs.glue-lang }}-${{ inputs.vim-version }}" in
          py311-v9.*)
            LDFLAGS=-rdynamic ./configure \
              --with-features=huge \
              --enable-fail-if-missing \
              --enable-largefile \
              --enable-multibyte \
              --enable-python3interp \
              --with-python3-command=python3.11 \
              --with-python3-stable-abi=3.11 \
              --enable-gui=no \
              --prefix="$HOME/vim/prefix"
            ;;
          py39-v8.*)
            env \
              vi_cv_path_python3_plibs="-L$(python3.9-config --configdir) -lpython3.9 -ldl -lm" \
              vi_cv_var_python3_version=3.9 \
              LDFLAGS=-rdynamic \
              ./configure \
              --with-features=huge \
              --enable-fail-if-missing \
              --enable-largefile \
              --enable-multibyte \
              --enable-python3interp \
              --with-python3-command=python3.9 \
              --with-python3-stable-abi=3.9 \
              --prefix="$HOME/vim/prefix"
            ;;
        esac
        make && make install
        echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
    - name: Download and install nvim to PATH
      if: ${{ inputs.vim-distr == 'nvim' && steps.cache-vim.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends curl tar
        case ${{ inputs.vim-version }} in
          v0.10.2)
            TARBALL_NAME=nvim-linux64
            ;;
          v0.11.5)
            TARBALL_NAME=nvim-linux-x86_64
            ;;
        esac
        mkdir ~/vim
        curl -fSL https://github.com/neovim/neovim/releases/download/${{ inputs.vim-version }}/${TARBALL_NAME}.tar.gz \
          | tar xzf - --strip-components=1 -C ~/vim
        echo "$HOME/vim/bin" >> $GITHUB_PATH
    - name: Add vim/nvim to PATH
      if: ${{ steps.cache-vim.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        case ${{ inputs.vim-distr }} in
          vim)
            echo "$HOME/vim/prefix/bin" >> $GITHUB_PATH
            ;;
          nvim)
            echo "$HOME/vim/bin" >> $GITHUB_PATH
            ;;
        esac
    - name: Print vim/nvim version
      shell: bash
      run: ${{ inputs.vim-distr }} --version
